### ISSUE TITLE
Wallet server groups should fetch from dsn servers

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-wallet#136]
As an example this file should fetch the groups from predefined dns endpoints 
https://github.com/block-core/blockcore-wallet/blob/58684b28706b2e5d3e4f4203db2c70bc345fc608/angular/src/shared/servers.ts

One example is 
https://ns.coinvault.io/docs/index.html

Fetching the endpoint
https://ns.coinvault.io/api/dns/services
will return 
```
["{Domain=crs.indexer.coinvault.io, IpAddress=172.19.0.2, Port=9930, Symbol=CRS, Service=Indexer, Ttl=20}","  
 {Domain=btc.indexer.coinvault.io, IpAddress=172.19.0.2, Port=9910, Symbol=BTC, Service=Indexer, Ttl=20}","  
 {Domain=strax.indexer.coinvault.io, IpAddress=172.19.0.2, Port=9920, Symbol=STRAX, Service=Indexer, Ttl=20}"]
```
Which could be translated to a group object
```
 group1: {
        'BTC': ['https://btc.indexer.coinvault.io'],
        'STRAX': ['https://strax.indexer.blockcore.net', 'https://strax.indexer.coinvault.io', 'https://strax.indexer.thedude.pro'],
        'TSTRAX': ['https://tstrax.indexer.blockcore.net'],
        'CRS': ['https://crs.indexer.blockcore.net', 'https://crs.indexer.coinvault.io', 'https://crs.indexer.thedude.pro'],
        'TCRS': ['https://tcrs.indexer.blockcore.net'],
        'CITY': ['https://city.indexer.blockcore.net'],
    },
```

**Comment by sondreb** [comment]
This has now been completed and the static indexer services list has been removed.

While the Blockcore DNS JS library has support for retrieving the nameserver list from a centralized web endpoint, we are not using this as it's a single point of failure. List of nameservers is part of the source code.
