### ISSUE TITLE
Add network definition for Legacy and SegWit (Bech32)

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#221]
Bitcoin (Yes)
City Chain (No)
Cirrus (No?)
Cybits (?)
RSC (?)
SBC (?)
Stratis (Yes?)
X42 (No?)

The dropdown that today defines the address type, this should probably be hidden in an advanced option.

**Comment by dangershony** [comment]
What about:
Bitcoin
Bitcoin (segwit)

**Comment by sondreb** [comment]
Yes, for Bitcoin we already have different network definitions:

![image](https://user-images.githubusercontent.com/309938/189458872-59c81314-db4b-4b0a-8f4c-68133a5b2725.png)

**Comment by sondreb** [comment]
This has been solved by having the address format, which changes both used address format and the purpose (44/84) derivation path.
