### ISSUE TITLE
Allow single key accounts

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#30]
The create account UI should support an advanced option of single key, where the user can enter the whole derivation path and the account will be marked "singleKey" or something similar.

Cirrus Core allows users to pick any of the 20 keys (addresses) to be used when making a wallet, we only support the first (0) index by default, but in the account UI a user can add alternatives for Cirrus Core (and potentially other services that relies on a single key).

**Comment by dangershony** [comment]
Isn't this simply to not gen a new address when we click on receive?
its basically just a flag or so.

**Comment by sondreb** [comment]
No, we need to allow users to create accounts with different address indexes (last part of the derivation path).

**Comment by sondreb** [comment]
So they will be allowed to choose any single key derived from the secret recovery phrase, not "just use the first".

**Comment by sondreb** [comment]
Moved this to beta, as this is likely something that will be done for CRS.

**Comment by sondreb** [comment]
This has been implemented and it's available on the network type and field named `singleAddress`.
