### ISSUE TITLE
Hide most options on account create

### ISSUE THREAD

**Issue by missmeowness** [block-core/blockcore-wallet#315]
Many of options basically should be hidden by default 
![image](https://user-images.githubusercontent.com/117081472/208299520-aecce651-de10-4362-88d5-e0eca8d68f69.png)

**Comment by IlonaGasiewska** [comment]
Hi, can you show me your code? I will try to help :)

**Comment by sondreb** [comment]
Hi, if you want to get started it is fairly easy. There are some instructions in the [README.md](README.md).

Basically clone with submodules
npm run setup
npm start

And then you must check the "Install Extension" part of the readme on how to manually load it locally (developer loading of extension).

Also please join our Discord for further assistance: https://www.blockcore.net/discord
