### ISSUE TITLE
Count key usage

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#318]
Every time a key is used it should be logged to a counter that should be displayed in the permission screen under settings.

**Comment by dangershony** [comment]
It should also track what dapp used it, so a dApp/key count

**Comment by sondreb** [comment]
Yes each permission is connected to specific app, so it will be on app and key level, so you'll know how many times "encrypt" has been executed.

The idea is to potentially add rate limiting and even alert/notifications inside the extension to users that "This app have used your key a lot the last hour".

**Comment by sondreb** [comment]
![image](https://user-images.githubusercontent.com/309938/208459755-37f01eb9-8520-4833-bdbc-15bf6f501b00.png)

**Comment by dangershony** [comment]
Ok this is great, we'll need something similar for every swap signature

**Comment by sondreb** [comment]
All permissions will get this feature automatically, so anything that requires consent will have this counter available.
