### ISSUE TITLE
transaction.send component 

### ISSUE THREAD

**Issue by dangershony** [block-core/blockcore-wallet#329]
If sending to a segwit address the  `this.sendService.transactionId` is null, not sure why.

In my example I used city chain

**Comment by dangershony** [comment]
I also got this error, this is on none segwit address also on city chain

![image](https://user-images.githubusercontent.com/7487930/215497868-1da0da4b-8e33-4e23-b652-17661ae58850.png)

**Comment by sondreb** [comment]
This is probably fix now?

**Comment by missmeowness** [comment]
This is likely fixed. Please, reopen issue if not fixed
