### ISSUE TITLE
Tool: Sign and Verify

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#55]
Add a tool under the "Tools" section on wallet dashboard that allow users to sign and verify messages.

The UI should allow users to pick account, then address, then either sign a message manually or verify it.

**Comment by missmeowness** [comment]
I have finished this task and code has been merged. Please add better verification UI

**Comment by sondreb** [comment]
I'll add some improved UI to show verification status, thank you for your contributions 👍🏼 🥇
