### ISSUE TITLE
Colour icons

### ISSUE THREAD

**Issue by drmathias** [block-core/blockcore-wallet#64]
Coloured account icons might be a nice way to add some colour into the UI and make it easier to visually differentiate between chains. One idea would be to store branding colours for each chain and apply these to the account icon. There could be two settings for the light/dark variant so that it fits with both UI themes.

![2022_02_02_0um_Kleki](https://picresize.com/images/t1rsz_152214421-d4af8e9a-5f09-4df9-9b04-262511f0e47c.png)
_(sorry my photo editing skills suck)_

**Comment by sondreb** [comment]
![image](https://github.com/block-core/blockcore-wallet/assets/309938/f367cbc9-6a25-42ba-be61-9741a1efd757)

![image](https://github.com/block-core/blockcore-wallet/assets/309938/6ec48e3d-9529-4165-ac98-de7f81e91ba9)

Coming in a pull request shortly.
