### ISSUE TITLE
Handle password and seeds with reset on timeout using session storage

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#78]
globalThis.chrome.storage.session is very new, but supported in stable browser releases now. Implement some logic to keep the passwords and seeds in session storage until timeout.

**Comment by dangershony** [comment]
Is there a documentation we can read about security?
I presume session storage is isolated only to the extension.

**Comment by sondreb** [comment]
Session storage is isolated to the extension yes, and I presume it is never persisted to disk but only kept in-memory. It's a very recent addition to the browser and little documentation available.
