### ISSUE TITLE
Validate the secret recovery phrase during recovery

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#79]
Currently the secret recovery phrase (mnemonic) is not being validated and any input is accepted.

**Comment by miladsoft** [comment]
Check each word you have written down on the BIP-39 words list: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by miladsoft** [comment]
You can use [jsbip39.js](https://github.com/iancoleman/jsbip39/blob/master/jsbip39.js):
https://github.com/iancoleman/jsbip39

**Comment by sondreb** [comment]
This has previously been updated to perform actual validation against all possible language lists.
