### ISSUE TITLE
Index 0 is not shown in the derivation parth

### ISSUE THREAD

**Issue by sondreb** [block-core/blockcore-wallet#9]
![image](https://user-images.githubusercontent.com/309938/128244158-a965ffb8-002e-4f39-99f7-fd927da93185.png)

The value 0 (index 0) is not shown in the derivation path when an account is selected. It is shown correctly when 1 or another value is used. This is likely due to number/string parsing, thinking "0" is equal to null/undefined/empty string.

**Comment by missmeowness** [comment]
![image](https://github.com/block-core/blockcore-wallet/assets/117081472/ba5915a9-e221-421e-a51c-355a2c0a1d8f)

Closing this issue. This is now working fine. It only shows 'index' now
